%% prepare data for multi-task learning model 
% feature_p   : features of photos
% feature_sv  : features of viewed sketches
% feature_s1  : features of 1 hour sketches
% feature_s24 : features of 24 hour sketches
% feature_suv : features of unviewed sketches
% index_train : index of training data
% index_test  : index of testing data
% Num         : number of subjects

function [xtrain, xtest, ytrain, irank, nx, ind_kf_train, ind_kx_train] = mtl_data(feature_p,feature_sv,feature_s1,feature_s24,feature_suv,index_train, index_test, i, Num)

ytrain = [feature_p(index_train,i);feature_p(index_train,i);feature_p(index_train,i);feature_p(index_train,i);...
    feature_sv(index_train,i);feature_sv(index_train,i);feature_sv(index_train,i);feature_s1(index_train,i);feature_s1(index_train,i);...
    feature_s24(index_train,i)]; % label
x = [feature_sv(:,i);feature_s1(:,i); feature_s24(:,i); feature_suv(:,i);...
    feature_s1(:,i); feature_s24(:,i);feature_suv(:,i);feature_s24(:,i);....
    feature_suv(:,i);feature_suv(:,i)]; % data
xtrain = x; % training data will be extract from the whole dataset according to the index of training data: ind_kx_train
xtest = [feature_sv(index_test,i);feature_s1(index_test,i); feature_s24(index_test,i); feature_suv(index_test,i);...
    feature_s1(index_test,i); feature_s24(index_test,i);feature_suv(index_test,i);feature_s24(index_test,i);....
    feature_suv(index_test,i);feature_suv(index_test,i)]; % testing data
ind_kf_train = [ones(numel(index_train),1);ones(numel(index_train),1)*2;ones(numel(index_train),1)*3;...
    ones(numel(index_train),1)*4;ones(numel(index_train),1)*5;ones(numel(index_train),1)*6;...
    ones(numel(index_train),1)*7;ones(numel(index_train),1)*8;ones(numel(index_train),1)*9;...
    ones(numel(index_train),1)*10]; % index for the label of training data
ind_kx_train = [index_train';(index_train+Num)';(index_train+Num*2)';(index_train+Num*3)'...
    ;(index_train+Num*4)';(index_train+Num*5)';(index_train+Num*6)';(index_train+Num*7)'...
    ;(index_train+Num*8)';(index_train+Num*9)'];  % index for training data
nx = ones(numel(ind_kf_train),1);
